services:
  api:
    build: ./api
    ports: 
      - 3000:3000
    environment:
      - PORT=3000
    volumes:
      - ./api/data:/app/data

  front-end:
    build: ./front-end
    ports:
      - 80:80